on: [push]

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-2022
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: build
      run: |
        cd $env:GITHUB_WORKSPACE
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX="install" || exit \b
        cmake --build build --config Release -j2 || exit \b

    - uses: actions/upload-artifact@v2
      with:
        name: opensim-creator-deps_amd64_windows.zip
        path: install/*
        if-no-files-found: error

  ubuntu2004:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: install mesa (OpenGL support)
      run: |
        sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: install libgtk-3-dev (nativefiledialog)
      run: sudo apt-get install libgtk-3-dev

    - name: build
      run: |
        set -xeuo pipefail
        cd $GITHUB_WORKSPACE
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX="install" -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j$(nproc)

    - uses: actions/upload-artifact@v2
      with:
        name: opensim-creator-deps_amd64_linux.tar.gz
        path: install/*
        if-no-files-found: error

  macCatalina:
    name: Build on Mac (catalina)
    runs-on: macos-11
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: run build script
      run: |
        set -xeuo pipefail
        cd $GITHUB_WORKSPACE
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX="install" -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j$(sysctl -n hw.physicalcpu)

    - uses: actions/upload-artifact@v2
      with:
        name: opensim-creator-deps_amd64_macos.tar.gz
        path: install/*
        if-no-files-found: error
